package net.runelite.client.plugins.microbot.hunterrumours.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import net.runelite.api.gameval.ItemID;
import net.runelite.api.NpcID;




@Getter
@RequiredArgsConstructor
@SuppressWarnings("deprecation") // NpcID is deprecated but still used in the Hunter Rumours plugin
public enum Creatures {

    TROPICAL_WAGTAIL(NpcID.TROPICAL_WAGTAIL, "Tropical Wagtail", ItemID.HG_TAILFEATHER, ItemID.HUNTING_OJIBWAY_BIRD_SNARE),
	WILD_KEBBIT(NpcID.WILD_KEBBIT, "Wild Kebbit", ItemID.HG_KEBBITTUFT, ItemID.KNIFE),
	SAPPHIRE_GLACIALIS(NpcID.SAPPHIRE_GLACIALIS, "Sapphire Glacialis", ItemID.HG_BUTTERFLYWING_BLUE, ItemID.HUNTING_BUTTERFLY_NET),

	SWAMP_LIZARD(NpcID.SWAMP_LIZARD, "Swamp Lizard", ItemID.HG_LIZARDCLAW, ItemID.NET),
	SPINED_LARUPIA(NpcID.SPINED_LARUPIA, "Spined Larupia", ItemID.HG_LARUPIA_EAR, ItemID.HUNTING_TEASING_STICK),
	BARB_TAILED_KEBBIT(NpcID.BARBTAILED_KEBBIT, "Barb-tailed Kebbit", ItemID.HG_KEBBITTUFT, ItemID.KNIFE),
	SNOWY_KNIGHT(NpcID.SNOWY_KNIGHT, "Snowy Knight", ItemID.HG_BUTTERFLYWING_WHITE, ItemID.HUNTING_BUTTERFLY_NET),
	PRICKLY_KEBBIT(NpcID.PRICKLY_KEBBIT, "Prickly Kebbit", ItemID.HG_KEBBITTUFT, ItemID.KNIFE),

	EMBERTAILED_JERBOA(NpcID.EMBERTAILED_JERBOA, "Embertailed Jerboa", ItemID.HG_JERBOATAIL_LARGE, ItemID.HUNTING_BOX_TRAP),  //TODO: VERIFY
	HORNED_GRAAHK(NpcID.HORNED_GRAAHK, "Horned Graahk", ItemID.HG_GRAAHK_HORN, ItemID.HUNTING_TEASING_STICK),
	SPOTTED_KEBBIT(NpcID.SPOTTED_KEBBIT, "Spotted Kebbit", ItemID.HG_KEBBITTUFT, ItemID.KNIFE),
	BLACK_WARLOCK(NpcID.BLACK_WARLOCK, "Black Warlock", ItemID.HG_BUTTERFLYWING_BLACK, ItemID.HUNTING_BUTTERFLY_NET),

	ORANGE_SALAMANDER(NpcID.ORANGE_SALAMANDER, "Orange Salamander", ItemID.HG_LIZARDCLAW_ORANGE, ItemID.NET),
	RAZOR_BACKED_KEBBIT(NpcID.KEBBIT, "Razor-backed Kebbit", ItemID.HG_KEBBITTUFT, ItemID.KNIFE), //TODO: VERIFY
	SABRE_TOOTHED_KEBBIT(NpcID.SABRETOOTHED_KEBBIT, "Sabre-toothed Kebbit", ItemID.HG_KEBBITTUFT, ItemID.KNIFE),
	GREY_CHINCHOMPA(NpcID.CHINCHOMPA, "Grey Chinchompa", ItemID.HG_CHINCHOMPATUFT, ItemID.HUNTING_BOX_TRAP),
	SABRE_TOOTHED_KYATT(NpcID.SABRETOOTHED_KYATT, "Sabre-toothed Kyatt", ItemID.HG_KYATTTOOTH, ItemID.KNIFE),
	DARK_KEBBIT(NpcID.DARK_KEBBIT, "Dark Kebbit", ItemID.HG_KEBBITTUFT, ItemID.COINS),
	PYRE_FOX(NpcID.PYRE_FOX, "Pyre Fox", ItemID.HG_FOXFLUFF, ItemID.KNIFE),
	RED_SALAMANDER(NpcID.RED_SALAMANDER, "Red Salamander", ItemID.HG_LIZARDCLAW_RED, ItemID.NET),
	RED_CHINCHOMPA(NpcID.CARNIVOROUS_CHINCHOMPA, "Carnivorous Chinchompa", ItemID.HG_CHINCHOMPATUFT_RED, ItemID.HUNTING_BOX_TRAP),
	RED_CHINCHOMPA_2(NpcID.CARNIVOROUS_CHINCHOMPA, "Red Chinchompa", ItemID.HG_CHINCHOMPATUFT_RED, ItemID.HUNTING_BOX_TRAP), 
	SUNLIGHT_MOTH(NpcID.SUNLIGHT_MOTH, "Sunlight Moth", ItemID.HG_MOTHWING_SUN, ItemID.HUNTING_BUTTERFLY_NET),
	DASHING_KEBBIT(NpcID.DASHING_KEBBIT, "Dashing Kebbit", ItemID.HG_KEBBITTUFT, ItemID.COINS),
	SUNLIGHT_ANTELOPE(NpcID.SUNLIGHT_ANTELOPE, "Sunlight Antelope", ItemID.HG_ANTELOPEHOOF_SUN, ItemID.KNIFE),
	MOONLIGHT_MOTH(NpcID.MOONLIGHT_MOTH, "Moonlight Moth", ItemID.HG_MOTHWING_MOON, ItemID.HUNTING_BUTTERFLY_NET),
	TECU_SALAMANDER(NpcID.TECU_SALAMANDER, "Tecu Salamander", ItemID.HG_LIZARDCLAW_MOUNTAIN, ItemID.NET),
	HERBIBOAR(NpcID.HERBIBOAR, "Herbiboar", ItemID.HG_HERBYTUFT, ItemID.COINS),
	MOONLIGHT_ANTELOPE(NpcID.MOONLIGHT_ANTELOPE, "Moonlight Antelope", ItemID.HG_ANTELOPEHOOF_MOON, ItemID.KNIFE),;
	
	@Getter
	private final int rumourNpcId;
	@Getter
	private final String rumourNpcName;
	@Getter
	private final int rareItemId;
	@Getter
	private final int trapItemId;

}
